# Generated by Django 2.2.28 on 2023-03-09 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuID', models.TextField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuItemID', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(default='None', max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('photo', models.ImageField(blank=True, upload_to='menu_item_images')),
                ('slug', models.SlugField(unique=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Menu')),
            ],
            options={
                'verbose_name_plural': 'MenuItems',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantID', models.CharField(max_length=128, unique=True)),
                ('location', models.CharField(default='None', max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='restaurant_images')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewID', models.CharField(max_length=128, unique=True)),
                ('comment', models.CharField(max_length=1000)),
                ('ratings', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='review_images')),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.MenuItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
